---
sections:
    - cover:
        files: cover
        html_options: 
            - --template=%{template_dir}/template-title.html
    - toc: 
        pdf_options:
            - --xsl-style-sheet toc.template.xsl
    - section:
        files: 
            - exec.md
            - intro.md
            - vulnerabilities.md
            - docinfo.md
            - hax.yaml
template: templates/colmancom
pdf_filename: btb_2017_test_report_short_v1.1.pdf

...
