html_global:
    html_options: 
        - '--standalone' 
        - '--css=css/template.css'
        - '--template=%{template_dir}/template.html'
    files: 'metadata.yaml'
    pandoc_filters: 
        - '%{template_dir}/formattedmetavars.py'
        - '%{template_dir}/metavars.py'  

pdf_global:
    pdf_options: 
        - '--page-size A4 -T 2.2cm -B 2.2cm -L 0cm -R 0cm'
        - '--header-html "file://%{html_dir}/header.html?classifcation=Commercial-in-Confidence"'
        - '--footer-html "file://%{html_dir}/footer.html?page=[page]&topage=[topage]&classifcation=Commercial-in-Confidence"'
        - '--print-media-type'
        - '--javascript-delay 100'

# These options are ignored, but knowing the margins can be useful because they're not all in the same place.
#margins:
#    top: '2.2cm'
#    bottom: '2.2cm'
#    left: '2.5cm'
#    right: '1.5cm'
